version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      libs:
        patterns:
          - "*"
    open-pull-requests-limit: 1
  - package-ecosystem: "maven"
    directory: "./custom-handlers/verifier-testbed"
    schedule:
      interval: "weekly"
    groups:
      libs:
        patterns:
          - "*"
    open-pull-requests-limit: 1